export const fakeData = [
    {
        title: "Rovectin Treatment Lotion",
        type: "toner",
        price: 11.99,
        status: "RP",
        rating: 9,
        comment: "dsfsdfjsakdjskfjsdv",
        day: true,
        night:true,
        dateEntered: "04/12/21",
    },
    {
        title: "Isntree Hylauronic Acid Aqua Gel Cream",
        type: "cream",
        price: 9.99,
        status: "MRP",
        rating: 7,
        comment: "dsfsdfjsakdjfgdfgsdfdfskfjsdv",
        day: true,
        night:false,
        dateEntered: "04/12/21",
    },
    {
        title: "Dermatory Cica Cream",
        type: "cream",
        price: 14.99,
        status: "MRP",
        rating: 8,
        comment: "sfgfhsdfdsdfjsakdjfgdfgsdfdfskfjsdv",
        day: false,
        night: true,
        dateEntered: "04/11/21",
    },
];