export const fakeData = [
    {
        title: "Melano CC ",
        type: "essence",
        price: 12.99,
        status: "WNRP",
        rating: 7,
        comment: "dsfsdfjsakdjskfjsdv",
        day: true,
        night:true,
        dateEntered: "04/12/21",
        id: "34gerr32rvb",
    },
    {
        title: "Rovectin Treatment Lotion",
        type: "toner",
        price: 11.99,
        status: "RP",
        rating: 9,
        comment: "dsfsdfjsakdjskfjsdv",
        day: true,
        night:true,
        dateEntered: "04/12/21",
        id: "fggrfi353f2",
    },
    {
        title: "Isntree Hylauronic Acid Aqua Gel Cream",
        type: "cream",
        price: 9.99,
        status: "MRP",
        rating: 7,
        comment: "dsfsdfjsakdjfgdfgsdfdfskfjsdv",
        day: true,
        night:false,
        dateEntered: "04/12/21",
        id: "3694berf23f",

    },
    {
        title: "Dermatory Cica Cream",
        type: "cream",
        price: 14.99,
        status: "MRP",
        rating: 8,
        comment: "sfgfhsdfdsdfjsakdjfgdfgsdfdfskfjsdv",
        day: false,
        night: true,
        dateEntered: "04/11/21",
        id: "34vff3e432d",
    },
    {
        title: "Real Barrier CicaRelief Toner",
        type: "toner",
        price: 12.99,
        status: "MRP",
        rating: 8,
        comment: "sdsdfssfgfhsdfdsdfjsakdjfgdfgsdfdfskfjsdv",
        day: true,
        night: true,
        dateEntered: "04/11/21",
        id: "543gfdvvds3",
    },
    {
        title: "Etude House SoonJung 5.5 foam cleanser",
        type: "cleanser",
        price: 7.99,
        status: "MRP",
        rating: 8,
        comment: "kljksdsdfssfgfjsakdjfgdfgsdfdfskfjsdv",
        day: true,
        night: false,
        dateEntered: "04/11/21",
        id: "42fvsdf3ff4",
    },
    {
        title: "Scinic Avocado Foam Cleanser",
        type: "cleanser",
        price: 8.99,
        status: "MRP",
        rating: 9,
        comment: "sdsdfssfgfhsdfdsdfjsakdjfgdfgsdfdfskfjsdv",
        day: false,
        night: true,
        dateEntered: "04/11/21",
        id: "6hbrrgerf39",
    },
    {
        title: "Skin1004 Madagascar Centella Toning Toner",
        type: "toner",
        price: 11.99,
        status: "MRP",
        rating: 10,
        comment: "sgfhsdfdsdfjsakdjfgdfgsdfdfskfjsdv",
        day: true,
        night: true,
        dateEntered: "04/11/21",
        id: "bjhmfgkfd34",
    },

];